allowBuilds:
  "@swc/core": true
  cbor-extract: true
  esbuild: true
  sharp: true
  unrs-resolver: true
overrides:
  brace-expansion: 5.0.9
  fast-uri: 3.1.4
  nanoid: 5.1.16
  postcss: ">=8.5.18"
  sharp: 0.35.3
  minimatch: ">=9.0.3"
  undici: 7.29.0
