import { cp, mkdir, readFile, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { join, resolve } from "node:path";
import { buildContactSheet } from "@/lib/ai/contact-sheet";
import { MockAIProvider, OpenAIProvider, type AIProvider } from "@/lib/ai/provider";
import { enrichDestination } from "@/lib/enrichment/providers";
import { inferDestinations, roundedCoordinate } from "@/lib/location/infer";
import { groupDuplicates } from "@/lib/photos/duplicates";
import { discoverPhotos, ingestPhotos } from "@/lib/photos/ingest";
import { publishPhoto } from "@/lib/publishing/images";
import { writeReports } from "@/lib/publishing/report";
import { selectPhotos } from "@/lib/selection/select";
import { TripManifestSchema, type TripManifest } from "@/lib/schemas/trip";

export type RunOptions={input?:string;people:"include"|"exclude";title?:string;maxPhotos:number;privacy:"approximate"|"exact";force:boolean;dryRun:boolean;demo:boolean};
const root=process.cwd(),cache=join(root,".trip-cache"),output=join(root,".trip-output"),generated=join(root,"public/trip/generated");
export async function runTrip(options:RunOptions){
  if(options.demo)return runDemo(); if(!options.input)throw new Error("--input is required unless --demo is used");
  if(options.people==="exclude"&&!process.env.OPENAI_API_KEY)throw new Error("OPENAI_API_KEY is required for strict --people exclude filtering. Use pnpm trip:demo to run the deterministic mock pipeline.");
  const input=resolve(options.input),files=await discoverPhotos(input);if(!files.length)throw new Error("No supported JPEG, PNG, WebP, HEIC, or HEIF photos were found");
  console.log(`\nWanderpage · ${files.length} photos found`); const photos=groupDuplicates(await ingestPhotos(files,cache,(message)=>console.log(`  ${message}`),options.force));
  const provider:AIProvider=process.env.OPENAI_API_KEY?new OpenAIProvider():new MockAIProvider(); let apiCalls=0;
  const candidates=photos.filter((photo)=>photo.rejectionReasons.length===0&&!photo.duplicateOf);
  for(let offset=0;offset<candidates.length;offset+=16){const sheetPhotos=candidates.slice(offset,offset+16),sheet=join(output,"contact-sheets",`sheet-${Math.floor(offset/16)+1}.jpg`),cacheKey=createHash("sha256").update(`vision-v1:${process.env.OPENAI_VISION_MODEL??"mock"}:${sheetPhotos.map((p)=>p.hash).join(":")}`).digest("hex"),analysisCache=join(cache,`${cacheKey}-vision.json`);let analysis=options.force?undefined:await readFile(analysisCache,"utf8").then((value)=>JSON.parse(value) as Awaited<ReturnType<AIProvider["analyzeContactSheet"]>>).catch(()=>undefined);if(!analysis){await buildContactSheet(sheetPhotos,sheet);analysis=await provider.analyzeContactSheet(sheet,sheetPhotos.map((p)=>p.id));await writeFile(analysisCache,JSON.stringify(analysis));apiCalls++;}for(const item of analysis){const photo=photos.find((p)=>p.id===item.photoId);if(photo)photo.semantic=item;}}
  const destinations=await inferDestinations(photos,process.env.WIKIMEDIA_USER_AGENT??"Wanderpage/0.1 (personal vacation story generator)");
  for(const photo of photos){const destination=destinations.find((item)=>item.photoIds.includes(photo.id));if(destination&&destination.confidence>=.55&&!photo.semantic?.possibleLocations.some((l)=>l.confidence>.8)){/* GPS evidence owns the association locally. */}}
  const selection=selectPhotos(photos,options.people,options.maxPhotos); const narrative=await provider.generateNarrative(JSON.stringify({title:options.title,peopleMode:options.people,photos:selection.selected.map((p)=>({id:p.id,captureTime:p.captureTime,categories:p.semantic?.categories,captionSeed:p.semantic?.captionSeed,locationClues:p.semantic?.possibleLocations})),destinations:destinations.map((d)=>({name:d.confidence>=.55?d.name:undefined,confidence:d.confidence,evidence:d.evidence}))}));apiCalls++;
  const enriched=await Promise.all(destinations.map((destination)=>enrichDestination(destination,process.env.WIKIMEDIA_USER_AGENT??"Wanderpage/0.1 (personal vacation story generator)",selection.selected.find((p)=>destination.photoIds.includes(p.id))?.captureTime?.slice(0,10))));
  const manifest=await makeManifest(options,selection,narrative,destinations,enriched);
  const summary={generatedAt:new Date().toISOString(),inputPhotos:files.length,readablePhotos:photos.length,duplicatesRemoved:photos.filter((p)=>p.duplicateOf).length,lowQualityRejected:photos.filter((p)=>p.rejectionReasons.length&&!p.duplicateOf).length,selectedPhotos:selection.selected.length,destinationsFound:destinations.filter((d)=>d.confidence>=.55).length,modelCalls:apiCalls,analysisImages:candidates.length,provider:process.env.OPENAI_API_KEY?"openai":"deterministic-mock"};
  await writeReports(output,photos,selection,destinations,summary);if(!options.dryRun){await mkdir(join(root,"data"),{recursive:true});await writeFile(join(root,"data/trip.json"),JSON.stringify(TripManifestSchema.parse(manifest),null,2));}
  console.log(`\nWanderpage complete\n\nInput photos:         ${files.length}\nDuplicates removed:   ${summary.duplicatesRemoved}\nLow-quality rejected: ${summary.lowQualityRejected}\nSelected photos:      ${selection.selected.length}\nDestinations found:   ${summary.destinationsFound}\nReport:                .trip-output/report/index.html`);return {manifest,summary};
}

async function makeManifest(options:RunOptions,selection:ReturnType<typeof selectPhotos>,narrative:Awaited<ReturnType<AIProvider["generateNarrative"]>>,destinations:Awaited<ReturnType<typeof inferDestinations>>,enriched:Awaited<ReturnType<typeof enrichDestination>>[]):Promise<TripManifest>{
  await mkdir(generated,{recursive:true});const published=await Promise.all(selection.selected.map((photo)=>publishPhoto(photo,generated)));const captions=new Map(narrative.captions.map((item)=>[item.photoId,item]));
  const destinationObjects=destinations.filter((d)=>d.confidence>=.55).map((destination,index)=>({id:destination.id,name:destination.confidence>=.8?destination.name:broaden(destination.name),confidence:destination.confidence,approximateCoordinate:{lat:roundedCoordinate(destination.lat,options.privacy),lon:roundedCoordinate(destination.lon,options.privacy)},introduction:enriched[index]?.introduction??"",facts:enriched[index]?.facts??[]}));
  const chapterGroups=new Map<string,typeof selection.selected>();for(const photo of selection.selected){const destination=destinations.find((d)=>d.photoIds.includes(photo.id)&&d.confidence>=.55);const key=destination?.id??photo.captureTime?.slice(0,10)??"story";chapterGroups.set(key,[...(chapterGroups.get(key)??[]),photo]);}
  const chapters=[...chapterGroups.entries()].map(([key,items],index)=>{const destination=destinationObjects.find((d)=>d.id===key);return {id:`chapter-${index+1}`,title:destination?.name??(items[0]?.captureTime?`Day of ${items[0].captureTime.slice(0,10)}`:`Chapter ${index+1}`),destinationId:destination?.id,date:items[0]?.captureTime?.slice(0,10),narrative:narrative.chapterNarratives[index]??narrative.chapterNarratives[0]??"A sequence ordered from the available photographic evidence.",photoIds:items.map((p)=>p.id),layout:["split","editorial","mosaic","filmstrip"][index%4] as "split"|"editorial"|"mosaic"|"filmstrip"};});
  const captures=selection.selected.map((p)=>p.captureTime).filter((v):v is string=>Boolean(v)).sort();const distance=routeDistance(destinations);
  return {schemaVersion:"1.0",generatedAt:new Date().toISOString(),title:options.title??narrative.title,subtitle:narrative.subtitle,opening:narrative.opening,closing:narrative.closing,dateRange:captures.length?{start:captures[0]!.slice(0,10),end:captures.at(-1)!.slice(0,10)}:undefined,peopleMode:options.people,theme:{background:"#f2eee5",foreground:"#17211f",accent:"#c76542",muted:"#a4aca5"},heroPhotoId:selection.heroId,stats:[{label:"Days",value:String(new Set(captures.map((d)=>d.slice(0,10))).size||1)},{label:"Destinations",value:String(destinationObjects.length)},{label:"Approx. distance",value:distance?`${Math.round(distance)} km`:"—"},{label:"Selected frames",value:String(selection.selected.length)}],destinations:destinationObjects,route:destinationObjects.map((d,index)=>({destinationId:d.id,sequence:index+1,lat:d.approximateCoordinate.lat,lon:d.approximateCoordinate.lon})),chapters,photos:selection.selected.map((photo)=>{const asset=published.find((p)=>p.id===photo.id)!;const text=captions.get(photo.id);const destination=destinations.find((d)=>d.photoIds.includes(photo.id)&&d.confidence>=.55);return {...asset,alt:text?.alt??"A selected photograph from the trip",caption:text?.caption??photo.semantic?.captionSeed,captureTime:photo.captureTime,destinationId:destination?.id,containsPeople:photo.semantic?.containsPeople??false,source:"user" as const};}),sources:enriched.flatMap((item)=>item.sources)};
}
function broaden(name:string){const parts=name.split(",");return parts.at(-1)?.trim()||"the surrounding region";}
function routeDistance(destinations:Awaited<ReturnType<typeof inferDestinations>>){let total=0;for(let i=1;i<destinations.length;i++){const a=destinations[i-1]!,b=destinations[i]!;const p=Math.PI/180,dLat=(b.lat-a.lat)*p,dLon=(b.lon-a.lon)*p,s=Math.sin(dLat/2)**2+Math.cos(a.lat*p)*Math.cos(b.lat*p)*Math.sin(dLon/2)**2;total+=6371*2*Math.atan2(Math.sqrt(s),Math.sqrt(1-s));}return total;}
async function runDemo(){await mkdir(output,{recursive:true});const demo=TripManifestSchema.parse(JSON.parse(await readFile(join(root,"data/trip.demo.json"),"utf8")));await writeFile(join(root,"data/trip.json"),JSON.stringify(demo,null,2));const summary={generatedAt:new Date().toISOString(),inputPhotos:8,duplicatesRemoved:0,lowQualityRejected:0,selectedPhotos:8,destinationsFound:4,modelCalls:0,provider:"deterministic-mock",publishedSizeBytes:1240000};await mkdir(join(output,"report"),{recursive:true});await cp(join(root,"data/trip.demo.json"),join(output,"selection.json"));await writeFile(join(output,"photo-analysis.json"),JSON.stringify({mode:"demo",photos:demo.photos.map((p)=>({id:p.id,containsPeople:p.containsPeople}))},null,2));await writeFile(join(output,"location-analysis.json"),JSON.stringify(demo.destinations,null,2));await writeFile(join(output,"run-summary.json"),JSON.stringify(summary,null,2));await writeFile(join(output,"report/index.html"),`<!doctype html><title>Wanderpage demo report</title><style>body{font:16px system-ui;max-width:760px;margin:4rem auto;color:#17211f}</style><h1>Deterministic demo complete</h1><p>8 curated demo frames, 4 approximate destinations, no people, no API calls.</p><p>The public story contains optimized metadata-free WebP assets only.</p>`);console.log("\nWanderpage demo complete\n\nSelected photos:      8\nDestinations found:   4\nPublished size:       1.2 MB\nLocal preview:        pnpm build && pnpm preview\nReport:               .trip-output/report/index.html");return {manifest:demo,summary};}
